# flightradar24 for QuantumultX
# v1.0.0 · 2026-09-28
# Flightradar24 Gold 订阅解锁 (365 天历史/去广告/无限追踪)
# 需先用免费账户登录
#
# 用法: 复制下方两段到你的 QuantumultX 配置

[filter_local]
hostname = mobile.flightradar24.com

[http_response]
^https?:\/\/mobile\.flightradar24\.com\/mobile\/(user-session|\w{9}) script-path=https://raw.githubusercontent.com/tedwcy/proxy-plugins/main/quantumultx/flightradar24/flightradar24.js, requires-body=true, tag=flightradar24, timeout=10